version: '3'
services:
  localphp:
    build: .
    container_name: localdevelop
    ports:
      - "8081:80"
    volumes:
      - ./app:/app
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
